### ISSUE TITLE
Add an `all` extension to allow all tags

### ISSUE THREAD

**Issue by ismail1432** [tgalopin/html-sanitizer#19]
Thank you @tgalopin for this great job !
I have a small idea, it could helpful to have an `all` extension to allow all tags instead write all of them
WDYT ?

`$sanitizer = Sanitizer::create(['extensions' => ['all']);`
will be a shortcut for 
`$sanitizer = Sanitizer::create(['extensions' => ['basic', 'code', 'image', 'list', 'table', 'iframe', 'extra']);`

**Comment by tgalopin** [comment]
Hello @ismail1432 !

Thanks for the kind feedback :) . However, I think this may lead to security issues because it would mean that by upgrading the sanitizer to the next minor version which adds a new extension, this extension would automatically be enabled, leading your application to allow more tags than what you would like. I much prefer being explicit at this level, I think the Sanitizer is already easy enough to instantiate :) .
