### ISSUE TITLE
Should empty tags be removed

### ISSUE THREAD

**Issue by jonnybarnes** [tgalopin/html-sanitizer#25]
If we provide the following HTML:
```
<p>Hello</p>
<img src="javascript:evil();" onload="evil();" />
```
Then pass it through html-sanitizer we get:
```
<p>Hello</p>
<img />
```

Should the `<img>` tag be taken out entirely now it has no attributes left?

**Comment by tgalopin** [comment]
Hello!

I don't think it should, but I may be wrong. Several tags (like br, hr, etc.) don't have attributes but still need to be kept :) .

**Comment by jonnybarnes** [comment]
I see where your coming from,  but tags like `br` and `hr` have semantic meaning in and of themselves. What is an `img` or an `iframe` if it son’t linking to anything?

**Comment by tgalopin** [comment]
I don't think it is the role of the sanitizer to do this. However, you can quite easily create your own extension to remove these tags if you really want to :) !

**Comment by ghost** [comment]
I too think there is a usecase for this. I'm ending up with a lot of `<p><span><br /></span></p><ul><li><span><br /></span></li>` kinda stuff (yeah, the input is terrible :) ). 

But understand if you don't see it in the scope of the lib. It's helping me out a bunch already where HtmlPurifier could not.

**Comment by tgalopin** [comment]
I see the issue. However, I think your issue is quite specific to your application, as the tags to remove are custom. Removing empty tags is really challenging to do in a generic and valid way.

I would suggest to leverage the features of the library though, it provides everything you need to do what you want quite efficiently. We can discuss that on the Symfony Slack (symfony.com/support) if you're interested, I would love to help on this :) !
