### ISSUE TITLE
How to prevent HTML encode (e.g @ => &#64;)

### ISSUE THREAD

**Issue by BackNot** [tgalopin/html-sanitizer#71]
Thank you for the library. 

I just have one question that I could not find an answer anywhere (so far). Is there any way to prevent HTML encode of the characters (e.g. prevent <  to transform to & lt; > to & gt; @ to & #64; etc.). I use the Symfony bundle (if it matters).

Thanks.

**Comment by tgalopin** [comment]
There is a very good reason this happens: it's the only safe way to protect yourself against XSS injections in all cases. I'm not sure why you would want to disable this behavior.

Could you tell me more about why you're looking to do this?

**Comment by BackNot** [comment]
Hi. Thanks for the quick response. 

I use the sanitize method on every data that is submitted just before it reaches the database. This leads to cases where user's email address is modified (e.g. johndoe@gmail.com => johndoe& #64;gmail.com).

Thanks.

**Comment by tgalopin** [comment]
You should probably not use the sanitizer this way: you should only sanitize data that you expect to display as-is (without escaping, "raw" in Twig) in a browser. Twig escaping is more than enough for all other data.

In the case of an email address, you should be able to validate it as en email on input (using a Symfony constraint) and display it in a mailto attribute using Twig escaping (enabled by default on Symfony).

**Comment by aramhovsepyan** [comment]
Hi Titouan,

Imho we should always both sanitize and escape (i.e., layered defence as a core security pattern). OWASP XSS prevention cheatsheet also recommends this approach. I would not be sleeping well if I knew that users can store XSS in the DB and just pray that somebody didn't by accident put the |raw filter somewhere.

So while using an email validator is indeed the right approach email fields that won't work with other simple text fields where users can input anything they'd like (e.g., "let's meet @ the Eiffel tower > 5pm").

The question is how good of an idea is it to sanitize -> htmlentities (and then twig escape turned on by default). Also whether this approach could be offered by a configuration in the sanitizer itself.

Thanks for the great library by the way :). The comparison with htmlpurifier is somewhat puzzling by the way. To me it seems that this library is just a better version of the htmlpurifier. Strictly speaking the sanitizer does purify the html by removing any potential garbage.

**Comment by tgalopin** [comment]
Hello @aramhovsepyan 

What @BackNot is asking is different from what you're talking about.

In your example, you're mentioning a generic user string you would store in the database. As you explain well, it's extremely important to escape it (ie to remove all characters that could be harmful and replace them with their corresponding HTML entity). Whether you do this at input (when persisting in the database) or at output (when displaying the content) doesn't matter: the important part is that you do escape user-generated content, all the time. You could even do it at both ends, even though that seems overkill (but that'd be fine).

@BackNot was mentioning a different feature: the ability **not** to escape a string when sanitizing it. I don't see a use-case where this would make sense. A sanitizer is meant to output a safe string, and such a "partially-safe" string wouldn't be useful.

Also, note that for sanitizing HTML, the aim is not to replace the HTML characters with their entities, because we do want to have working HTML as an output. The sanitizer only escapes text strings. That's also why you should apply the sanitizer **both** before persisting in database and before displaying in the browser.

Finally, for you question regarding HtmlPurifier: https://github.com/tgalopin/html-sanitizer/blob/master/docs/4-comparison-with-htmlpurifier.md

I'm closing this issue as I don't see the point of the feature request, but if I'm wrong feel free to tell me.
